import {
  MessageSquare,
  Users,
  Book,
  ScrollText,
  Wallet,
  Shield,
  Settings,
  LogOut,
  X,
  Check,
  Plus,
  Minus,
  RefreshCw,
  Play,
  Pause,
  Square,
  Zap,
  Cpu,
  HardDrive,
  Globe,
  Target,
  Swords,
  Hammer,
  Gavel,
  ClipboardList,
  Lightbulb,
  Ship,
  ShoppingCart,
  NotebookPen,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  messageSquare: MessageSquare,
  users: Users,
  book: Book,
  scrollText: ScrollText,
  wallet: Wallet,
  shield: Shield,
  settings: Settings,
  logOut: LogOut,
  x: X,
  check: Check,
  plus: Plus,
  minus: Minus,
  refreshCw: RefreshCw,
  play: Play,
  pause: Pause,
  square: Square,
  zap: Zap,
  cpu: Cpu,
  hardDrive: HardDrive,
  globe: Globe,
  target: Target,
  swords: Swords,
  hammer: Hammer,
  gavel: Gavel,
  clipboardList: ClipboardList,
  lightbulb: Lightbulb,
  ship: Ship,
  shoppingCart: ShoppingCart,
  notebookPen: NotebookPen,
}
